name: Tests and Style Check

on:
  push:
    branches:
      - main
  pull_request:

env:
  POETRY_VERSION: "1.8.1"
  POETRY_URL: https://install.python-poetry.org

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
      # See: https://github.com/actions/setup-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        # 実際にインストールされた正確なバージョン（ x.y.x ）をキャッシュのキーで利用する
        id: setup_python
      # See: https://github.com/actions/cache
      - name: Cache Packages
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      # Poetry そのものをインストールする
      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | \
            python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      # パッケージをインストールする
      - name: Install Dependencies
        run: poetry install --no-interaction
      # テストを実行する
      - name: Run Tests
        run: poetry run pytest tests/
  black:
    name: Check code style with Black
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # See: https://github.com/actions/setup-python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        # 実際にインストールされた正確なバージョン（ x.y.x ）をキャッシュのキーで利用する
        id: setup_python
      # See: https://github.com/actions/cache
      - name: Cache Packages
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      # Poetry そのものをインストールする
      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | \
            python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      # パッケージをインストールする
      - name: Install Dependencies
        run: poetry install --no-root
      # Black でのチェックを実行する
      - name: Check code style with Black
        run: poetry run black --check --diff .
